### ISSUE TITLE
Unterstützungs-Seite für Contao 4.4 optimieren

### ISSUE THREAD

**Issue by ff1601com** [1601com/core-bundle#4]
Hey @vm1601com,

bei der Unterstützungs-Seite ist das Styling für die Contao-Version 4.4 etwas verschoben.
Wirkt so, als würden die Schriftarten etwas zu groß sein.

Kannst Du das bitte noch anpassen?
Würde das ganze als Minor-Change auf 1.0.1 (o. ä) laufen lassen.

Danke!

**Comment by vm1601com** [comment]
@ff1601com habe das Styling für den Button angepasst und meine Änderungen gepusht.

Für alles Weitere übergebe ich wieder an dich.

**Comment by ff1601com** [comment]
Danke dir @vm1601com.

Kurze Frage noch. Mir war bei einem C44 noch etwas aufgefallen:
![image](https://user-images.githubusercontent.com/40162179/99500860-38777080-297b-11eb-992b-961775b9cf36.png)

Würdest du das mit CSS lösen oder den Text kürzen?

**Comment by vm1601com** [comment]
Würde vllt allgemein den Text etwas kürzen und auf jeden Fall dann noch per CSS umbrechen lassen.

**Comment by ff1601com** [comment]
ToDos:
- [ ] Text kürzen
- [ ] Umbruch über Styling einfügen
- [x] Used-Report / Core-Bundle über User-Rechte abwählbar machen
![image](https://user-images.githubusercontent.com/40162179/99651553-0cc9b880-2a57-11eb-9776-7a42f83eab66.png)

**Comment by vm1601com** [comment]
@ff1601com habe das Styling für 4.9 und 4.4 angepasst. Glaube das ist jetzt die schönste Variante.

Habe gerade gesehen, da sind noch andere Punkte nicht eingecheckt. Ich überlasse dir das Einchecken, dann kannst du das gleich mit der neuen Version kombinieren.
